function [trainedClassifier, validationAccuracy] = trainBaggedAllPower(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 28-May-2020 18:09:27


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'std_x', 'std_y', 'std_z', 'shapefactor_x', 'shapefactor_y', 'shapefactor_z', 'rms_x', 'rms_y', 'rms_z', 'mean_x', 'mean_y', 'mean_z', 'skewness_x', 'skewness_y', 'skewness_z', 'kurtosis_x', 'kurtosis_y', 'kurtosis_z', 'peaktorms_x', 'peaktorms_y', 'peaktorms_z', 'fd-std_x', 'fd-std_y', 'fd-std_z', 'fd-shapefactor_x', 'fd-shapefactor_y', 'fd-shapefactor_z', 'fd-rms_x', 'fd-rms_y', 'fd-rms_z', 'fd-mean_x', 'fd-mean_y', 'fd-mean_z', 'fd-skewness_x', 'fd-skewness_y', 'fd-skewness_z', 'fd-peak2peak_x', 'fd-peak2peak_y', 'fd-peak2peak_z', 'fd-peaktorms_x', 'fd-peaktorms_y', 'fd-peaktorms_z', 'fd-max_x', 'fd-max_y', 'fd-max_z'};
predictors = inputTable(:, predictorNames);
response = inputTable.Power;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', 38113);
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'Bag', ...
    'NumLearningCycles', 30, ...
    'Learners', template, ...
    'ClassNames', [10; 20; 30; 40; 50; 60; 70; 80; 90; 100]);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'fd-max_x', 'fd-max_y', 'fd-max_z', 'fd-mean_x', 'fd-mean_y', 'fd-mean_z', 'fd-peak2peak_x', 'fd-peak2peak_y', 'fd-peak2peak_z', 'fd-peaktorms_x', 'fd-peaktorms_y', 'fd-peaktorms_z', 'fd-rms_x', 'fd-rms_y', 'fd-rms_z', 'fd-shapefactor_x', 'fd-shapefactor_y', 'fd-shapefactor_z', 'fd-skewness_x', 'fd-skewness_y', 'fd-skewness_z', 'fd-std_x', 'fd-std_y', 'fd-std_z', 'kurtosis_x', 'kurtosis_y', 'kurtosis_z', 'mean_x', 'mean_y', 'mean_z', 'peaktorms_x', 'peaktorms_y', 'peaktorms_z', 'rms_x', 'rms_y', 'rms_z', 'shapefactor_x', 'shapefactor_y', 'shapefactor_z', 'skewness_x', 'skewness_y', 'skewness_z', 'std_x', 'std_y', 'std_z'};
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2020a.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'std_x', 'std_y', 'std_z', 'shapefactor_x', 'shapefactor_y', 'shapefactor_z', 'rms_x', 'rms_y', 'rms_z', 'mean_x', 'mean_y', 'mean_z', 'skewness_x', 'skewness_y', 'skewness_z', 'kurtosis_x', 'kurtosis_y', 'kurtosis_z', 'peaktorms_x', 'peaktorms_y', 'peaktorms_z', 'fd-std_x', 'fd-std_y', 'fd-std_z', 'fd-shapefactor_x', 'fd-shapefactor_y', 'fd-shapefactor_z', 'fd-rms_x', 'fd-rms_y', 'fd-rms_z', 'fd-mean_x', 'fd-mean_y', 'fd-mean_z', 'fd-skewness_x', 'fd-skewness_y', 'fd-skewness_z', 'fd-peak2peak_x', 'fd-peak2peak_y', 'fd-peak2peak_z', 'fd-peaktorms_x', 'fd-peaktorms_y', 'fd-peaktorms_z', 'fd-max_x', 'fd-max_y', 'fd-max_z'};
predictors = inputTable(:, predictorNames);
response = inputTable.Power;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Set up holdout validation
cvp = cvpartition(response, 'Holdout', 0.25);
trainingPredictors = predictors(cvp.training, :);
trainingResponse = response(cvp.training, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', 38113);
classificationEnsemble = fitcensemble(...
    trainingPredictors, ...
    trainingResponse, ...
    'Method', 'Bag', ...
    'NumLearningCycles', 30, ...
    'Learners', template, ...
    'ClassNames', [10; 20; 30; 40; 50; 60; 70; 80; 90; 100]);

% Create the result struct with predict function
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
validationPredictFcn = @(x) ensemblePredictFcn(x);

% Add additional fields to the result struct


% Compute validation predictions
validationPredictors = predictors(cvp.test, :);
validationResponse = response(cvp.test, :);
[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);

% Compute validation accuracy
correctPredictions = (validationPredictions == validationResponse);
isMissing = isnan(validationResponse);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
